import type { Metadata } from "next";
import Link from "next/link";
import "@/app/globals.css";

import Navbar from "@/components/ui/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative antialiased overflow-x-hidden overflow-y-auto max-w-full bg-gradient-to-bl from-orange-600 to-orange-900">
        <Navbar />
        <main className="w-full max-w-full">{children}</main>
        <footer className="flex flex-col w-full items-center justify-center text-center text-orange-600">
          <div className="hidden sm:flex px-10 w-full items-center justify-between text-white">
            <p>© CITRUS ARC STUDIO</p>
            <p>202503267271 (003780123-A)</p>
          </div>
          <Link href="/">
            <h2 className="text-6xl sm:text-[180px] font-bold leading-none translate-y-[-18px]">
              CITRUS ARC STUDIO
            </h2>
          </Link>
        </footer>
      </body>
    </html>
  );
}
